name: sonarscanworkflow
on:
  workflow_call:
    inputs:
      repocheckout:
        required: false
        type: string
        default: ""
      projdir:
        required: false
        type: string
        default: ${{ github.workspace }}
    secrets:
      sonartoken:
        required: false
jobs:
  SCS:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repocheckout }}
      - name: sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonartoken }}
        with:
          projectBaseDir: ${{ inputs.projdir }}
          args: >
            -Dsonar.organization=testorg-yrk
            -Dsonar.projectKey=testorg-yrk
            -D=coverage.xml
            -Dsonar.verbos=true
            -Dsonar.projectDescription=${{ github.repository_id }}
